/*
 * G6502 - 6502 Emulator
 * Copyright (C) 2016  Ignacio Sanchez Gines

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/
 *
 */

#ifndef G6502_OPCODENAMES_H_
#define	G6502_OPCODENAMES_H_

#include "g6502_definitions.h"

namespace g6502
{

#ifdef G6502_DISASM

static const char* kOPCodeNames[256] = {
    "BRK",
    "ORA $(%2%1,X)",
    "KIL",
    "SLO $(%2%1,X)",
    "NOP $%1",
    "ORA $%1",
    "ASL $%1",
    "SLO $%1",
    "PHP",
    "ORA #$%1",
    "ASL A",
    "ANC #$%1",
    "NOP $%2%1",
    "ORA $%2%1",
    "ASL $%2%1",
    "SLO $%2%1",

    "BPL $%3",
    "ORA ($%1),Y",
    "KIL",
    "SLO ($%1),Y",
    "NOP $%1,X",
    "ORA $%1,X",
    "ASL $%1,X",
    "SLO $%1,X",
    "CLC",
    "ORA $%2%1,Y",
    "NOP",
    "SLO $%2%1,Y",
    "NOP $%2%1,X",
    "ORA $%2%1,X",
    "ASL $%2%1,X",
    "SLO $%2%1,X",

    "JSR $%2%1",
    "AND $(%2%1,X)",
    "KIL",
    "RLA $(%2%1,X)",
    "BIT $%1",
    "AND $%1",
    "ROL $%1",
    "RLA $%1",
    "PLP",
    "AND #$%1",
    "ROL",
    "ANC #$%1",
    "BIT $%2%1",
    "AND $%2%1",
    "ROL $%2%1",
    "RLA $%2%1",

    "BMI $%3",
    "AND ($%1),Y",
    "KIL",
    "RLA ($%1),Y",
    "NOP $%1,X",
    "AND $%1,X",
    "ROL $%1,X",
    "RLA $%1,X",
    "SEC",
    "AND $%2%1,Y",
    "NOP",
    "RLA $%2%1,Y",
    "NOP $%2%1,X",
    "AND $%2%1,X",
    "ROL $%2%1,X",
    "RLA $%2%1,X",

    "RTI",
    "EOR $(%2%1,X)",
    "KIL",
    "SRE $(%2%1,X)",
    "NOP $%1",
    "EOR $%1",
    "LSR $%1",
    "SRE $%1",
    "PHA",
    "EOR #$%1",
    "LSR",
    "ALR #$%1",
    "JMP $%2%1",
    "EOR $%2%1",
    "LSR $%2%1",
    "SRE $%2%1",

    "BVC $%3",
    "EOR ($%1),Y",
    "KIL",
    "SRE ($%1),Y",
    "NOP $%1,X",
    "EOR $%1,X",
    "LSR $%1,X",
    "SRE $%1,X",
    "CLI",
    "EOR $%2%1,Y",
    "NOP",
    "SRE $%2%1,Y",
    "NOP $%2%1,X",
    "EOR $%2%1,X",
    "LSR $%2%1,X",
    "SRE $%2%1,X",

    "RTS",
    "ADC $(%2%1,X)",
    "KIL",
    "RRA $(%2%1,X)",
    "NOP $%1",
    "ADC $%1",
    "ROR $%1",
    "RRA $%1",
    "PLA",
    "ADC #$%1",
    "ROR",
    "ARR #$%1",
    "JMP ($%2%1)",
    "ADC $%2%1",
    "ROR $%2%1",
    "RRA $%2%1",

    "BVS $%3",
    "ADC ($%1),Y",
    "KIL",
    "RRA ($%1),Y",
    "NOP $%1,X",
    "ADC $%1,X",
    "ROR $%1,X",
    "RRA $%1,X",
    "SEI",
    "ADC $%2%1,Y",
    "NOP",
    "RRA $%2%1,Y",
    "NOP $%2%1,X",
    "ADC $%2%1,X",
    "ROR $%2%1,X",
    "RRA $%2%1,X",

    "NOP #$%1",
    "STA $(%2%1,X)",
    "NOP #$%1",
    "SAX $(%2%1,X)",
    "STY $%1",
    "STA $%1",
    "STX $%1",
    "SAX $%1",
    "DEY",
    "NOP #$%1",
    "TXA",
    "XAA #$%1",
    "STY $%2%1",
    "STA $%2%1",
    "STX $%2%1",
    "SAX $%2%1",

    "BCC $%3",
    "STA ($%1),Y",
    "KIL",
    "AHX ($%1),Y",
    "STY $%1,X",
    "STA $%1,X",
    "STX $%1,Y",
    "SAX $%1,Y",
    "TYA",
    "STA $%2%1,Y",
    "TXS",
    "TAS $%2%1,Y",
    "SHY $%2%1,X",
    "STA $%2%1,X",
    "SHX $%2%1,Y",
    "AHX $%2%1,Y",

    "LDY #$%1",
    "LDA $(%2%1,X)",
    "LDX #$%1",
    "LAX $(%2%1,X)",
    "LDY $%1",
    "LDA $%1",
    "LDX $%1",
    "LAX $%1",
    "TAY",
    "LDA #$%1",
    "TAX",
    "LAX #$%1",
    "LDY $%2%1",
    "LDA $%2%1",
    "LDX $%2%1",
    "LAX $%2%1",

    "BCS $%3",
    "LDA ($%1),Y",
    "KIL",
    "LAX ($%1),Y",
    "LDY $%1,X",
    "LDA $%1,X",
    "LDX $%1,Y",
    "LAX $%1,Y",
    "CLV",
    "LDA $%2%1,Y",
    "TSX",
    "LAS $%2%1,Y",
    "LDY $%2%1,X",
    "LDA $%2%1,X",
    "LDX $%2%1,Y",
    "LAX $%2%1,Y",

    "CPY #$%1",
    "CMP $(%2%1,X)",
    "NOP #$%1",
    "DCP $(%2%1,X)",
    "CPY $%1",
    "CMP $%1",
    "DEC $%1",
    "DCP $%1",
    "INY",
    "CMP #$%1",
    "DEX",
    "CMP #$%1",
    "CPY $%2%1",
    "CMP $%2%1",
    "DEC $%2%1",
    "DCP $%2%1",

    "BNE $%3",
    "CMP ($%1),Y",
    "KIL",
    "DCP ($%1),Y",
    "NOP $%1,X",
    "CMP $%1,X",
    "DEC $%1,X",
    "DCP $%1,X",
    "CLD",
    "CMP $%2%1,Y",
    "NOP",
    "NOP $%2%1,X",
    "DCP $%2%1,Y",
    "CMP $%2%1,X",
    "DEC $%2%1,X",
    "DCP $%2%1,X",

    "CPX #$%1",
    "SBC $(%2%1,X)",
    "NOP #$%1",
    "ISC $(%2%1,X)",
    "CPX $%1",
    "SBC $%1",
    "INC $%1",
    "ISC $%1",
    "INX",
    "SBC #$%1",
    "NOP",
    "SBC #$%1",
    "CPX $%2%1",
    "SBC $%2%1",
    "INC $%2%1",
    "ISC $%2%1",

    "BEQ $%3",
    "SBC ($%1),Y",
    "KIL",
    "ISC ($%1),Y",
    "NOP $%1,X",
    "SBC $%1,X",
    "INC $%1,X",
    "ISC $%1,X",
    "SED",
    "SBC $%2%1,Y",
    "NOP",
    "ISC $%2%1,Y",
    "NOP $%2%1,X",
    "SBC $%2%1,X",
    "INC $%2%1,X",
    "ISC $%2%1,X"
};

#endif

} // namespace g6502

#endif // G6502_OPCODENAMES_H_

